// AngularAppBySuraj/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  standalone: true,
})
export class HomeComponent {}

<div class="wrap">
  <div class="content">
    <h1>Angular App By Suraj</h1>
    <img
      src="assets/IMG_20240330_173828-transformed.jpeg"
      alt="Suraj Kumal"
      width="500px"
    />
  </div>
</div>

// ReactAppBySuraj/src/components/Home.jsx
import React from "react";
import myPhoto from "../assets/SurajKumal.jpeg";
import "./style.css";
const Home = () => {
  return (
    <div className="home">
      <div className="wrap">
        <h1>React App By Suraj</h1>
        <img src={myPhoto} alt="My Photo" width="500px" />
      </div>
    </div>
  );
};

export default Home;
