// ReactAppBySuraj/src/components/Calculator.jsx
// Calculator.js
import React, { useState } from "react";
import Navbar from "./Navbar";
const Calculator = () => {
  const [num1, setNum1] = useState("");
  const [num2, setNum2] = useState("");
  const [operator, setOperator] = useState("add");
  const [result, setResult] = useState("");

  const handleCompute = () => {
    let computedResult;
    switch (operator) {
      case "add":
        computedResult = parseFloat(num1) + parseFloat(num2);
        break;
      case "subtract":
        computedResult = parseFloat(num1) - parseFloat(num2);
        break;
      case "multiply":
        computedResult = parseFloat(num1) * parseFloat(num2);
        break;
      default:
        computedResult = "";
    }
    setResult(computedResult);
  };

  return (
    <div>
      {<Navbar />}
      <div className="calculator">
      <h1>Calculator</h1>
      <form onSubmit={(e) => e.preventDefault()}>
        <input
          type="number"
          value={num1}
          onChange={(e) => setNum1(e.target.value)}
        />
        <select value={operator} onChange={(e) => setOperator(e.target.value)}>
          <option value="add">Add</option>
          <option value="subtract">Subtract</option>
          <option value="multiply">Multiply</option>
        </select>
        <input
          type="number"
          value={num2}
          onChange={(e) => setNum2(e.target.value)}
        />
        <button onClick={handleCompute}>Compute</button>
      </form>
      <p>Result: {result}</p>
    </div>
    </div>
  );
};

export default Calculator;

// AngularAppBySuraj/src/app/calculator/calculator.component.ts
// calculator.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css'],
})
export class CalculatorComponent {
  result: number | null = null;

  compute() {
    const num1 = parseFloat(
      (<HTMLInputElement>document.getElementById('num1')).value
    );
    const num2 = parseFloat(
      (<HTMLInputElement>document.getElementById('num2')).value
    );
    const operation = (<HTMLSelectElement>document.getElementById('operation'))
      .value;

    switch (operation) {
      case 'add':
        this.result = num1 + num2;
        break;
      case 'subtract':
        this.result = num1 - num2;
        break;
      case 'multiply':
        this.result = num1 * num2;
        break;
      default:
        this.result = null;
    }
  }
}

<!-- calculator.component.html -->
<div class="wrap">
  <h2>Simple Calculator</h2>
  <form id="calculatorForm">
    <label for="num1">Number 1:</label>
    <input type="number" id="num1" name="num1" required />
    <br />
    <label for="num2">Number 2:</label>
    <input type="number" id="num2" name="num2" required />
    <br />
    <label for="operation">Operation:</label>
    <select id="operation" name="operation" required>
      <option value="add">Add</option>
      <option value="subtract">Subtract</option>
      <option value="multiply">Multiply</option>
    </select>
    <br />
    <button type="button" (click)="compute()">Compute</button>
  </form>
  <div id="result">Result : {{ result }}</div>
</div>
